[package]
name = "app-mock"
version = "0.1.0"
edition = "2024"
description = "Desktop simulator for the embedded audio player UI"

[dependencies]
app-core = { workspace = true }
critical-section = { workspace = true, features = ["std"] }
embassy-executor = { workspace = true, features = [
  "platform-std",
  "executor-thread",
] }
embassy-futures = { workspace = true }
embassy-sync = { workspace = true }
embassy-time = { workspace = true, features = ["std"] }
embedded-graphics = { workspace = true }
embedded-graphics-simulator = { workspace = true }
heapless = { workspace = true }