use embedded_graphics::pixelcolor::Gray8;
use embedded_graphics::prelude::*;
use embedded_graphics_simulator::sdl2::Keycode;
use embedded_graphics_simulator::{
    OutputSettingsBuilder, SimulatorDisplay, SimulatorEvent, Window,
};

use app_core::event::{Button, Event, Screen};
use app_core::player::Player;
use app_core::playlist::Playlist;
use app_core::track::Track;
use app_core::ui::display_config::{DISPLAY_HEIGHT, DISPLAY_WIDTH, PIXEL_SCALE, PIXEL_SPACING};
use app_core::ui::screen_manager::ScreenManager;

fn main() {
    let mut display: SimulatorDisplay<Gray8> =
        SimulatorDisplay::new(Size::new(DISPLAY_WIDTH, DISPLAY_HEIGHT));

    let output_settings = OutputSettingsBuilder::new()
        .scale(PIXEL_SCALE)
        .pixel_spacing(PIXEL_SPACING)
        .build();

    let mut window = Window::new(
        &format!(
            "Audio Player Simulator — {DISPLAY_WIDTH}×{DISPLAY_HEIGHT} ({PIXEL_SCALE}× scale)"
        ),
        &output_settings,
    );

    let mut playlist = Playlist::new();
    let _ = playlist.add(Track {
        title: "Clair de Lune",
        artist: "Claude Debussy",
        duration_ms: 354000,
        file_path: "/music/flac/clair_de_lune.flac",
    });
    let _ = playlist.add(Track {
        title: "Gymnopédie No.1",
        artist: "Erik Satie",
        duration_ms: 210000,
        file_path: "/music/flac/gymnopedie_no1.flac",
    });

    let mut player = Player::new(playlist);
    let mut screen_manager = ScreenManager::default();
    let mut needs_refresh = true;

    // Emit initial state events so the first screen gets track metadata
    player.initialize();
    for event in player.event_queue() {
        screen_manager.handle_event(&event);
        needs_refresh = true;
    }

    // Initial draw to initialise the SDL window
    screen_manager.draw(&mut display);
    window.update(&display);

    loop {
        for event in window.events() {
            match event {
                SimulatorEvent::Quit => return,

                SimulatorEvent::KeyDown { keycode, .. } => {
                    let app_event = match keycode {
                        Keycode::Space => Some(Event::ButtonPress(Button::Play)),
                        Keycode::M => Some(Event::ButtonPress(Button::Menu)),
                        Keycode::N => Some(Event::ButtonPress(Button::Next)),
                        Keycode::P => Some(Event::ButtonPress(Button::Prev)),
                        Keycode::Num1 => Some(Event::ButtonPress(Button::Seek(10))),
                        Keycode::Num2 => Some(Event::ButtonPress(Button::Seek(20))),
                        Keycode::Num3 => Some(Event::ButtonPress(Button::Seek(30))),
                        Keycode::Num4 => Some(Event::ButtonPress(Button::Seek(40))),
                        Keycode::Num5 => Some(Event::ButtonPress(Button::Seek(50))),
                        Keycode::Num6 => Some(Event::ButtonPress(Button::Seek(60))),
                        Keycode::Num7 => Some(Event::ButtonPress(Button::Seek(70))),
                        Keycode::Num8 => Some(Event::ButtonPress(Button::Seek(80))),
                        Keycode::Num9 => Some(Event::ButtonPress(Button::Seek(90))),
                        Keycode::Num0 => Some(Event::ButtonPress(Button::Seek(0))),
                        _ => None,
                    };
                    if let Some(e) = app_event {
                        screen_manager.handle_event(&e);
                    }
                }

                _ => {}
            }
        }

        // === Event cascade: alternate drain until both queues are empty ===
        let mut progress = true;
        while progress {
            progress = false;

            // Drain active screen queue -> forward Player commands to Player
            for event in screen_manager.event_queue() {
                match event {
                    Event::Player(_) => {
                        player.handle_event(&event);
                        progress = true;
                    }
                    Event::Ui(Screen::Refresh) => {
                        needs_refresh = true;
                    }
                    Event::Ui(Screen::Change(_)) => {
                        screen_manager.handle_event(&event);
                        needs_refresh = true;
                    }
                    _ => {}
                }
            }

            // Drain Player queue -> forward state changes back to ScreenManager
            for event in player.event_queue() {
                screen_manager.handle_event(&event);
                progress = true;
            }
        }

        // Advance playback time ONCE per frame
        player.tick(33);

        // Drain events generated by the tick
        for event in player.event_queue() {
            screen_manager.handle_event(&event);
            needs_refresh = true;
        }
        for event in screen_manager.event_queue() {
            if let Event::Ui(Screen::Refresh) = event {
                needs_refresh = true;
            }
        }

        // Draw only if something changed
        if needs_refresh {
            screen_manager.draw(&mut display);
            window.update(&display);
            needs_refresh = false;
        }

        // ~30 fps
        std::thread::sleep(std::time::Duration::from_millis(33));
    }
}
